version: "3.8"
services:
  spboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=burhan
      - RABBITMQ_DEFAULT_PASS=123456